apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprofile-db-pvc
  labels:
    project: vprofile
    app: vprofile-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  # change the storage class name to hostpath when running in kube cluster within docker-desktop locally
  storageClassName: default
